# Generated by Django 5.1.2 on 2025-10-01 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_room_status_alter_room_image_alter_room_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='source',
            field=models.CharField(choices=[('walk_in', 'Walk-in'), ('website', 'Website'), ('agent', 'Travel Agent'), ('corporate', 'Corporate')], default='website', max_length=20),
        ),
    ]
